AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Asmbly Volunteer Dashboard - Persistence Layer
  DynamoDB Table definition.

Parameters:
  AppEnv:
    Type: String
    Description: Deployment Environment (dev, staging, prod)
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev
  Application:
    Type: String
    Description: Application Name for tagging
    Default: asmbly-volunteer-dashboard

Resources:
  VolunteerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      Tags:
        - Key: Application
          Value: !Ref Application
        - Key: Environment
          Value: !Ref AppEnv
      TableName: !Sub "VolunteerTable-${AppEnv}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  TableName:
    Value: !Ref VolunteerTable
    Description: DynamoDB Table Name
